In [1]:
import numpy as np
import pandas as pd

In [2]:
my_data = [1970,1979,1960]
my_index = ['USA','FRANCE','CIV']

In [3]:
dt_pandas = pd.Series(my_data, my_index)
dt_pandas

USA       1970
FRANCE    1979
CIV       1960
dtype: int64

In [4]:
dt_pandas["CIV"]

1960

In [5]:
dico_age={'Loss':29, 'Isho':31,'Aicha':17}
dico_panda_age = pd.Series(dico_age)

In [6]:
dico_panda_age

Loss     29
Isho     31
Aicha    17
dtype: int64



---
# partie 2

---

In [7]:
# Données de ventes (inventés) pour les 1er et 2e trimestres pour une entreprise mondiale
q1 = {'Japan': 80, 'China': 450, 'India': 200, 'USA': 250}
q2 = {'Brazil': 100,'China': 500, 'India': 210,'USA': 260}

In [8]:
seris_q1 = pd.Series(q1)
seris_q2 = pd.Series(q2)
seris_q1

Japan     80
China    450
India    200
USA      250
dtype: int64

In [9]:
seris_q2

Brazil    100
China     500
India     210
USA       260
dtype: int64

In [10]:
firs_half= seris_q2.add(seris_q1, fill_value=0)
firs_half

Brazil    100.0
China     950.0
India     410.0
Japan      80.0
USA       510.0
dtype: float64

In [11]:
firs_half.dtype

dtype('float64')



---
#DATAFRAME


---

In [13]:
#creation de DataFrame
np.random.seed(101)
dataDf = np.random.randint(1,101,(4,3))
dataDf

array([[96, 12, 82],
       [71, 64, 88],
       [76, 10, 78],
       [41,  5, 64]])

In [14]:
df1=pd.DataFrame(dataDf)
df1

    0   1   2
0  96  12  82
1  71  64  88
2  76  10  78
3  41   5  64

In [15]:
index = ["CA","NY","CX","TD"]
colonne = ["Janv","Fev","Mars"]

In [16]:
df2 = pd.DataFrame(dataDf,index,colonne)
df2

    Janv  Fev  Mars
CA    96   12    82
NY    71   64    88
CX    76   10    78
TD    41    5    64

In [18]:
pwd

'C:\\Users\\sangarea\\Desktop\\learning'

In [19]:
ls

 Le volume dans le lecteur C n’a pas de nom.
 Le numéro de série du volume est 6086-BC09

 Répertoire de C:\Users\sangarea\Desktop\learning

14/10/2023  11:58    <DIR>          .
14/10/2023  10:18    <DIR>          ..
14/10/2023  11:57    <DIR>          .ipynb_checkpoints
14/10/2023  11:58           140 032 Pandas_1.ipynb
               1 fichier(s)          140 032 octets
               3 Rép(s)  179 223 060 480 octets libres

In [20]:
df = pd.read_csv('/content/drive/MyDrive/APPRENTISAGE MACHINE LEARNING/Datasets/tips.csv')
df

FileNotFoundError: [Errno 2] No such file or directory: '/content/drive/MyDrive/APPRENTISAGE MACHINE LEARNING/Datasets/tips.csv'

In [65]:
df.columns

Index(['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size',
       'price_per_person', 'Payer Name', 'CC Number', 'Payment ID'],
      dtype='object')

In [66]:
df.index

RangeIndex(start=0, stop=244, step=1)

In [69]:
df.head()

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,Sun2959
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230,Sun4608
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6011812112971322,Sun4458
3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4676137647685994,Sun5260
4,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,4832732618637221,Sun2251

In [71]:
df.head(10)

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,Sun2959
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230,Sun4608
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6011812112971322,Sun4458
3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4676137647685994,Sun5260
4,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,4832732618637221,Sun2251
5,25.29,4.71,Male,No,Sun,Dinner,4,6.32,Erik Smith,213140353657882,Sun9679
6,8.77,2.00,Male,No,Sun,Dinner,2,4.38,Kristopher Johnson,2223727524230344,Sun5985
7,26.88,3.12,Male,No,Sun,Dinner,4,6.72,Robert Buck,3514785077705092,Sun8157
8,15.04,1.96,Male,No,Sun,Dinner,2,7.52,Joseph Mcdonald,3522866365840377,Sun6820
9,14.78,3.23,Male,No,Sun,Dinner,2,7.39,Jerome Abbott,3532124519049786,Sun3775

In [74]:
df.tail(3)

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
241,22.67,2.00,Male,Yes,Sat,Dinner,2,11.34,Keith Wong,6011891618747196,Sat3880
242,17.82,1.75,Male,No,Sat,Dinner,2,8.91,Dennis Dixon,4375220550950,Sat17
243,18.78,3.00,Female,No,Thur,Dinner,2,9.39,Michelle Hardin,3511451626698139,Thur672

In [80]:
df.describe()

       total_bill         tip        size  price_per_person     CC Number
count  244.000000  244.000000  244.000000        244.000000  2.440000e+02
mean    19.785943    2.998279    2.569672          7.888197  2.563496e+15
std      8.902412    1.383638    0.951100          2.914234  2.369340e+15
min      3.070000    1.000000    1.000000          2.880000  6.040679e+10
25%     13.347500    2.000000    2.000000          5.800000  3.040731e+13
50%     17.795000    2.900000    2.000000          7.255000  3.525318e+15
75%     24.127500    3.562500    3.000000          9.390000  4.553675e+15
max     50.810000   10.000000    6.000000         20.270000  6.596454e+15

In [84]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   total_bill        244 non-null    float64
 1   tip               244 non-null    float64
 2   sex               244 non-null    object
 3   smoker            244 non-null    object
 4   day               244 non-null    object
 5   time              244 non-null    object
 6   size              244 non-null    int64
 7   price_per_person  244 non-null    float64
 8   Payer Name        244 non-null    object
 9   CC Number         244 non-null    int64
 10  Payment ID        244 non-null    object
dtypes: float64(3), int64(2), object(6)
memory usage: 21.1+ KB

In [87]:
df.describe().transpose()

,count,mean,std,min,25%,50%,75%,max
total_bill,244.0,1.978594e+01,8.902412e+00,3.070000e+00,1.334750e+01,1.779500e+01,2.412750e+01,5.081000e+01
tip,244.0,2.998279e+00,1.383638e+00,1.000000e+00,2.000000e+00,2.900000e+00,3.562500e+00,1.000000e+01
size,244.0,2.569672e+00,9.510998e-01,1.000000e+00,2.000000e+00,2.000000e+00,3.000000e+00,6.000000e+00
price_per_person,244.0,7.888197e+00,2.914234e+00,2.880000e+00,5.800000e+00,7.255000e+00,9.390000e+00,2.027000e+01
CC Number,244.0,2.563496e+15,2.369340e+15,6.040679e+10,3.040731e+13,3.525318e+15,4.553675e+15,6.596454e+15